import { Html, Head, Main, NextScript } from 'next/document';
import Script from 'next/script';


export default function Document() {

  return (
    <html lang="en">
      <head>
        <title>Saudi Electricity</title>
      </head>
      <body suppressHydrationWarning={true}>
        <Main />
        <NextScript />
      </body>
    </html>
  );
}


// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
